name: Run Valuation Script

on:
  workflow_dispatch:
    inputs:
      x:
        description: 'Value for x'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Run Python script
      run: |
        python valuation.py ${{ github.event.inputs.x }}
